import type { Metadata, Viewport } from 'next'
import { Toaster } from 'sonner';
import './globals.css'
import { Ubuntu } from 'next/font/google';
import Sidebar from '@/components/Sidebar';
import Navbar from '@/components/Navbar';

const ubuntu = Ubuntu({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-ubuntu',
  weight: ['300', '400', '500', '700']
});

export const metadata: Metadata = {
  title: 'Aman Portfolio',
  description: 'Generated by Aman',
}

export const viewport: Viewport = {
  themeColor: "#4f46e5",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <main className="min-h-screen flex bg-[#163a5c] p-10">
          <div className="hidden lg:block sticky top-0 h-full">
            <Sidebar />
          </div>
          <div className="w-full ">
            
            <div className="overflow-hidden">
              {children}
            </div>
          </div>
        </main>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  )
}
