import type { Metadata, Viewport } from "next";
import { Toaster } from "sonner";
import "./globals.css";
import { Ubuntu } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import MobNavbar from '../components/MobNavbar';

const ubuntu = Ubuntu({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-ubuntu",
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Aman Portfolio",
  description: "Generated by Aman",
};

export const viewport: Viewport = {
  themeColor: "#4f46e5",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} bg-[#163a5c]`}>
        <main className="min-h-screen flex flex-col lg:flex-row p-8">
          <div className="lg:sticky top-0 w-full lg:w-auto lg:h-full mb-8 lg:mb-0">
            <Sidebar />
          </div>
          <div className="flex-1 h-screen">
            {children}
          </div>
          <MobNavbar/>
        </main>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
